### ISSUE TITLE
Lava level is not being handled well...

### ISSUE THREAD

**Issue by Zsashas** [Valiec/DeeperCaves#30] opened 2016-01-05 06:59 UTC
Whenever I enter that layer, my console is filled to nearly the point of freezing with this:

[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 94, 10, 122
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 91, 22, 121
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 101, 17, 121
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 97, 43, 127
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 90, 43, 124
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 101, 17, 125
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 96, 46, 126
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 100, 32, 131
[22:57:22] [Server thread/INFO] [STDOUT]: [com.kpabr.DeeperCaves.world.biome.DeeperDecorator:func_150513_a:233]: Lava: 90, 9, 123
[22:57:22] [Server thread/INFO] [STDOUT]:

**Comment by Valiec** [comment] 2016-01-07 20:34
The "Lava: x, y, z" messages are a debug feature I left in by accident. Regarding the lag, it is generating a lot of lava. I have not figured out a way to speed up world gen in that level.

**Comment by Valiec** [comment] 2016-03-31 19:01
Since the issue is simply caused by the large number of individual lava "springs" that generate on that level, I currently do not know if there is a way to fix this without removing a significant amount of the lava from the level. Therefore, I am closing this for now. If I find a way to fix the lag without removing the lava from the Lava level, I'll reopen this.

Also, I _have_ fixed the console spam.

**Closed by Valiec** 2016-03-31 19:01 UTC
Labels: bug, wontfix
